# -*- coding: utf-8 -*-
"""calidad del aire.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FUJMdDoyoCV6x4TdDE7BJXS9RGdHpwQb
"""

<<<import pandas as pd
import numpy as np
import pylab as pl
import seaborn as sns

data = pd.read_csv('/content/drive/MyDrive/calidad del aire/estacion-kennedy1.csv', delimiter=';', index_col=[0], decimal=',')
data.head()

data.info()

from google.colab import drive
drive.mount('/content/drive')

data.describe()

columnas_a_convertir = ['PM10', 'PM2.5', 'CO', 'NO', 'NO2', 'NOX', 'SO2', 'HR', 'OZONO', 'BBP', 'BC ug/m3']
for columna in columnas_a_convertir:
    data[columna] = pd.to_numeric(data[columna], errors='coerce')

medias = data[columnas_a_convertir].mean()
print("Medias de las columnas convertidas:")
print(medias)

medias = data[columnas_a_convertir].std()
print("Desviacion estandar de las columnas convertidas:")
print(medias)

fig = pl.figure(figsize=(3,3))
pl.hist(data['PM10'], color='green', histtype='step')
pl.axvline(data['PM10'].mean(), c='black', linestyle='-.', label='Promedio')
pl.legend()
pl.xlabel('PM10 [µg/m3]')
pl.ylabel('Conteos')
pl.title('Histograma de PM10', fontsize=15)
pl.grid()

fig = pl.figure(figsize=(3,3))
pl.hist(data['PM2.5'], color='yellow', histtype='step')
pl.axvline(data['PM2.5'].mean(), c='black', linestyle='-.', label='Promedio')
pl.legend()
pl.xlabel('PM2.5 [µg/m3]')
pl.ylabel('Conteos')
pl.title('Histograma de PM2.5', fontsize=15)
pl.grid()

fig = pl.figure(figsize=(3,3))
pl.hist(data['NOX'], color='purple', histtype='step')
pl.axvline(data['NOX'].mean(), c='black', linestyle='-.', label='Promedio')
pl.legend()
pl.xlabel('NOX [PPM]')
pl.ylabel('Conteos')
pl.title('Histograma de NOX', fontsize=15)
pl.grid()

fig = pl.figure(figsize=(3,3))
pl.hist(data['NO'], color='orange', histtype='step')
pl.axvline(data['NO'].mean(), c='black', linestyle='-.', label='Promedio')
pl.legend()
pl.xlabel('NO [PPB]')
pl.ylabel('Conteos')
pl.title('Histograma de NO', fontsize=15)
pl.grid()

fig = pl.figure(figsize=(3,3))
pl.hist(data['NO2'], color='red', histtype='step')
pl.axvline(data['NO2'].mean(), c='black', linestyle='-.', label='Promedio')
pl.legend()
pl.xlabel('NO2 [PPB]')
pl.ylabel('Conteos')
pl.title('Histograma de NO2', fontsize=15)
pl.grid()
fig = pl.figure(figsize=(3,3))

fig = pl.figure(figsize=(3,3))
pl.hist(data['NOX'], color='purple', histtype='step')
pl.axvline(data['NOX'].mean(), c='black', linestyle='-.', label='Promedio')
pl.legend()
pl.xlabel('NOX [PPM]')
pl.ylabel('Conteos')
pl.title('Histograma de NOX', fontsize=15)
pl.grid()

data['PM10'].fillna(data['PM10'].mean(), inplace=True)
Q1 = data['PM10'].quantile(0.25)
Q2 = data['PM10'].quantile(0.50)
Q3 = data['PM10'].quantile(0.75)
print(Q1, Q2, Q3)

IQR = Q3 - Q1
print(IQR)

ii = data.PM10 < Q1 - 1.5*IQR
jj = data.PM10 > Q3 + 1.5*IQR

sum(ii), sum(jj)

data.PM10[ii | jj]

_ = pl.boxplot(data.PM10)

data['PM2.5'].fillna(data['PM2.5'].mean(), inplace=True)
Q1 = data['PM2.5'].quantile(0.25)
Q2 = data['PM2.5'].quantile(0.50)
Q3 = data['PM2.5'].quantile(0.75)
print(Q1, Q2, Q3)

IQR = Q3 - Q1
print(IQR)

ii = data['PM2.5'] < Q1 - 1.5*IQR
jj = data['PM2.5'] > Q3 + 1.5*IQR

sum(ii), sum(jj)

data['PM2.5'][ii | jj]

_ = pl.boxplot(data['PM2.5'])

fig = pl.figure(figsize=(3,3))
sns.histplot(data.PM10, kde=True)

data.drop('PM10', axis=1)

_ = pl.violinplot(data['PM10'], quantiles=[0.25,0.5,0.75])

_ = pl.violinplot(data['PM2.5'], quantiles=[0.25,0.5,0.75])

# Gráfico de dispersión

from scipy.stats import pearsonr

def corrfunc(x, y, ax=None, **kws):
    """Plot the correlation coefficient in the top left hand corner of a plot."""
    r, _ = pearsonr(x, y)
    ax = ax or pl.gca()
    ax.annotate(f'ρ = {r:.2f}', xy=(.1, .9), xycoords=ax.transAxes)

fig=pl.figure(figsize=(3,3))
pp = sns.pairplot(data)
pp.map_lower(corrfunc)

